version: "3"

services:
  traefik:
    image: traefik:v2.0
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
    networks:
      - net
    ports:
      - 80:80
      - 8080:8080

  api:
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - net
    environment:
      HOST: 0.0.0.0
      PORT: 3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.${BASE_DOMAIN}`)"
      - "traefik.http.services.api.loadbalancer.server.port=3000"

networks:
  net:
